### ISSUE TITLE
Example heaplog.yml

### ISSUE THREAD

**Issue by umer936** [lezhnev74/heaplog#1]
Hi! 

I'm trying this using the docker-compose.yml from the README but I'm unable to get it to show me any logs in the GUI if I search anything. 

Maybe an example of heaplog.yml in the README would be good. 

Thank you! 

```yaml
# heaplog.yml

FilesGlobPattern: "/logs/*.log"    # Example path for log files
StoragePath: "/storage"              # Path to store index and data

# Regular expression to identify the start of log messages (required)
MessageStartRe: "^\\[(\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2})\\]"

# Date format inside the log message (required)
# DateFormat: "2006-01-02T15:04:05"
DateFormat: "2006-01-02 15:04:05,000"
```

```yaml 
# docker-compose.yml 

services:
  heaplog:
    image: lezhnev74/heaplog
    volumes:
      - /var/log:/logs:ro
      - ./storage:/storage:rw
      - ./heaplog.yml:/heaplog.yml:ro
    entrypoint: [ "/heaplog", "run" ]
    ports:
      - 8393:8393
```

**Comment by lezhnev74** [comment]
Hey Umer, try this docker-compose.yml:
```
services:
  heaplog:
    image: lezhnev74/heaplog
    volumes:
      - /var/log:/logs:ro
      - ./storage:/storage:rw
      - ./heaplog.yml:/heaplog.yml:ro
    entrypoint: [ "/heaplog" ]
    command: ["run"]
    ports:
      - 8393:8393
```      

now run `docker compose run heaplog test`. It should test your config against your log files and tell you if it found any messages. If it does that is a good start.
